[WIP] Switch to new infrastructure + eessi.io repo
EESSI/filesystem-layer pull request #160
Opened 2023-09-29 13:47 UTC by bedroge

2023-11-09 11:44 UTC, boegel requested changes
One small suggested change to drop the `latest` symlink, looks good to me otherwise!

@bedroge Will you have time to create & adopt a new repo key, so we can move forward with this ASAP?

2023-11-09 12:19 UTC, bedroge commented on roles/create_cvmfs_content_structure/vars/software.eessi.io.yml
> +  latest: versions/2023.06
Done in https://github.com/EESSI/filesystem-layer/pull/160/commits/83d02b04c650d502aa324a003be1c6f39786452c.

2023-11-09 12:26 UTC, bedroge commented
> One small suggested change to drop the `latest` symlink, looks good to me otherwise!
> 
> @bedroge Will you have time to create & adopt a new repo key, so we can move forward with this ASAP?

I've removed the `latest` symlink, and solved the merge conflict. I'll try to regenerate the keys today.

2023-11-11 10:47 UTC, boegel approved these changes

2023-11-11 10:47 UTC, merged