add Dockerfile for container providing easy access to 2020.08 EESSI pilot repository
EESSI/filesystem-layer pull request #35
Opened 2020-09-04 14:17 UTC by boegel

Doesn't include `fuse-overlayfs`, since pure clients don't really need that.

2020-09-21 07:03 UTC, boegel commented
@bedroge Let's merge this, container for clients that want to play with the pilot repo has proved to be working well?

2020-09-21 07:12 UTC, bedroge requested changes
Looks good to me, except that I have another PR (#36) which also adds files to this containers dir. That PR uses a README.md, though. Can we try making them compatible, by for instance renaming your README to README.md and describing this container in a specific section?

2020-09-21 07:12 UTC, bedroge commented on containers/README
> +see https://hub.docker.com/repository/docker/eessi/client-pilot and https://eessi.github.io/docs/pilot .
You will really have to make my day first ;-)

```suggestion
see https://hub.docker.com/repository/docker/eessi/client-pilot and https://eessi.github.io/docs/pilot.
```

2020-10-13 08:47 UTC, boegel commented
@bedroge I think this is good to go now...

2020-10-13 12:20 UTC, bedroge requested changes

2020-10-13 12:20 UTC, bedroge commented on containers/Dockerfile.EESSI-client-pilot-centos7
> + && yum install -y cvmfs-config-eessi-0.2.1-1.noarch.rpm
I think we don't need to download this rpm manually (also prevents it from being stored in the root, which is annoying for autocompletion ;-) )?
```suggestion
 && yum install -y https://github.com/EESSI/filesystem-layer/releases/download/v0.2.1/cvmfs-config-eessi-0.2.1-1.noarch.rpm 
```

2020-10-13 12:20 UTC, bedroge commented on containers/README.md
> +see https://hub.docker.com/repository/docker/eessi/client-pilot and https://eessi.github.io/docs/pilot .
```suggestion
see https://hub.docker.com/repository/docker/eessi/client-pilot and https://eessi.github.io/docs/pilot.
```
I don't like spaces, make my day again! :-D

2020-10-15 15:14 UTC, bedroge approved these changes
Haven't been able to test the Arm image on my RPi, but it looks good to me.

2020-10-15 15:15 UTC, merged